"use client";

import { useState } from "react";
import Link from "next/link";

import { SCRIPT_BYTES, SCRIPT_SENDS_TO, SCRIPT_SHA256, SCRIPT_VERSION } from "@/app/api/script/manifest";

/**
 * One line that says what is published, printed on every trust page.
 *
 * Version, size, fingerprint, and where a stock sheet sends. The same things a
 * student can read off their own sheet under `Blotter → Check this sheet`, so
 * a thing they hold can be held up against a thing on the page. Every value is
 * generated by `courier/publish.js`; nothing here is typed.
 *
 * The fingerprint is shown as its first and last eight characters, with the
 * whole string one click away, because sixty-four hex characters on a phone is
 * a wall and the ends are what a person compares anyway.
 */
export function ReceiptStub({ className = "" }: { className?: string }) {
  const [full, setFull] = useState(false);
  const sha = SCRIPT_SHA256;
  const short = `${sha.slice(0, 8)}…${sha.slice(-8)}`;
  const sendsTo = SCRIPT_SENDS_TO;

  return (
    <div className={`border-y border-rule py-3 font-mono text-[12px] leading-[1.6] text-ink-muted ${className}`}>
      <Link href="/code" className="grid grid-cols-2 gap-x-4 gap-y-1 hover:text-ink sm:flex sm:flex-wrap sm:gap-x-3">
        <span>Version {SCRIPT_VERSION}</span>
        <span className="hidden sm:inline text-ink-faint">·</span>
        <span>{SCRIPT_BYTES.toLocaleString("en-US")} bytes</span>
        <span className="hidden sm:inline text-ink-faint">·</span>
        <span title={sha} className={full ? "col-span-2 break-all" : ""}>
          SHA-256 {full ? sha : short}
        </span>
        <span className="hidden sm:inline text-ink-faint">·</span>
        {/* The full address, exactly as the sheet prints it. A grid cell does
            not wrap an unbroken URL on its own, so it spans the row on a phone
            and may break anywhere. */}
        <span className="col-span-2 break-all sm:col-auto">Sends to {sendsTo}</span>
      </Link>
      <button
        type="button"
        onClick={() => setFull((v) => !v)}
        className="mt-1 text-[12px] text-navy-500 underline underline-offset-4 hover:text-navy-900"
      >
        {full ? "Shorten the fingerprint" : "Show the whole fingerprint"}
      </button>
    </div>
  );
}
