import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Schibsted_Grotesk } from "next/font/google";
import "./globals.css";

import { AnalyticsProvider } from "@/components/analytics-provider";

/*
 * The display face, added August 5, 2026 after Jon twice flagged the type as
 * flat. Schibsted Grotesk was drawn for a news publisher, so it carries
 * editorial authority at large sizes and has real character in its terminals
 * and apertures, where Geist is deliberately neutral. It is a system decision,
 * not a one-off: it sets every headline and the Section 2 statement, and Geist
 * keeps the body and the interface.
 */
const displaySans = Schibsted_Grotesk({
  variable: "--font-schibsted",
  subsets: ["latin"],
});

/*
 * Roboto exists on this page for one reason: the Section 2 asset is a Gmail
 * surface and Gmail is set in Roboto. It is scoped to that component through
 * `--font-gmail` and is not part of the page's type system.
 */
const roboto = Roboto({
  variable: "--font-gmail",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * The canonical origin. Absolute URLs are required for share cards: a platform
 * fetching this page has no base to resolve `/opengraph-image` against.
 */
const SITE = "https://blotterib.com";

const TITLE = "Blotter, the recruiting tracker that stays current";
const DESCRIPTION =
  "Blotter keeps the Google Sheet you already use current, reading recruiting activity from Gmail and Calendar so you do not miss follow-ups, coffee chats, or next steps.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: TITLE,
  description: DESCRIPTION,

  /*
    SEARCH INDEXING, opened August 11, 2026.

    This read `robots: { index: false, follow: false }` under a WS5 rule:
    "private and unpublished throughout, keep the page out of indexes until the
    final simultaneous-launch authorization." **That rule's premise expired.**
    It was written when this was a private build with no domain and no traffic;
    Jon is now promoting the page.

    Jon challenged it directly and was right to. The argument he gave — more
    cold search traffic — is the weaker one: a new domain with no backlinks
    ranks for essentially nothing for months, so indexing buys close to no
    search traffic in the timeframe that matters.

    **The argument that actually carries it is recall.** Someone reads a Reddit
    post, does not click, and searches "Blotter IB" three days later. Unindexed,
    they find nothing. That is not cold traffic, it is the highest-intent search
    there is, on an audience the promotion has already paid to reach.

    The cost, accepted knowingly: search results and caches are durable in a way
    a link is not. Section 6 states what Blotter reads, retains and cannot
    touch for a system that does not exist yet, and `app/robots.ts` is deleted
    with this change, so nothing else holds the page back.
  */
  robots: { index: true, follow: true },

  alternates: { canonical: SITE },

  /*
    THE SHARE CARD.

    Production served a description and nothing else — no `og:image`, no
    `og:title`, no `twitter:card` — so every link posted to Reddit, X or
    LinkedIn rendered as a bare URL. On the channel this test depends on, that
    matters more than indexing does.

    The image itself is generated by `app/opengraph-image.tsx`; Next wires it
    into `og:image` and `twitter:image` automatically at these dimensions, so
    they are not repeated here.
  */
  openGraph: {
    type: "website",
    url: SITE,
    siteName: "Blotter",
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${displaySans.variable} ${roboto.variable} h-full`}
    >
      <body className="min-h-full font-sans">
        {/*
          Connects PostHog to the analytics adapter, or does nothing at all if
          no key is configured. It renders no markup and must stay above the
          page so the sink is installed as early as possible.
        */}
        <AnalyticsProvider />
        {children}
      </body>
    </html>
  );
}
